import Footer from "@/components/footer/Footer";
import { SessionProvider } from "next-auth/react";
import { PropsWithChildren } from "react";
import "./globals.css";
import Header from "./header";
import Providers from "./providers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body className="overflow-x-hidden">
        <Providers>
          <Header />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
